name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: read Package.json
      uses: rexdefuror/read-package-json@v1.0.5

    - run: echo "name - ${{ env.PACKAGE_NAME }}"
    - run: echo "version - ${{ env.PACKAGE_VERSION }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t omada-dns:${{ env.PACKAGE_VERSION }} -t omada-dns:latest .
      
    - name: Push Docker versioned image
      run: docker push omada-dns:${{ env.PACKAGE_VERSION }}

    - name: Push Docker latest image
      run: docker push omada-dns:latest

    - name: Cleanup
      run: docker logout

